export const languageNames = [
    {code: "en", displayName: "English"},
    {code: "fa", displayName: "فارسی" },
    {code: "cn", displayName: "中文"}
]

export const translationObject: TranslateObject = {
    en: {
        "Reap": "Reap",
        "Sow": "Sow",
        "Up": "Up",
        "Down": "Down",
        "Left": "Left",
        "Right": "Right",
        "Undo": "Undo",
        "Redo": "Redo",
        "Plant Species": "Plant Species",
        "Aloe Vera": "Aloe Vera",
        "Wheat": "Wheat",
        "Venus Flytrap": "Venus Flytrap",
        "Water Level": "Water Level",
        "Sun Level": "Sun Level",
        "Growth Level": "Growth Level",
        "Save": "Save",
        "Load": "Load",
        "Next Turn": "Next Turn",
        "Slot One": "Slot One",
        "Slot Two": "Slot Two",
        "Slot Three": "Slot Three",
        "Slot Four": "Slot Four",
        "Language": "Language",
        "Select a plant species": "Select a plant species",
        "Select a Language": "Select a Language",
        "Cell i": "Cell i",
        "Cell j": "Cell j",
        "Planterbox": "Planterbox",
        "Game is automatically saved after every turn, but you can manually save at any point": "Game is automatically saved after every turn, but you can manually save at any point"
    },
    cn: {
        "Reap" : "收割",
        "Sow" : "播种",
        "Up" : "上",
        "Down" : "下",
        "Left" : "左",
        "Right" : "右",
        "Undo" : "撤销",
        "Redo" : "重做",
        "Plant Species" : "植物种类",
        "Aloe Vera" : "芦荟",
        "Wheat" : "小麦",
        "Venus Flytrap" : "捕蝇草",
        "Water Level" : "水位",
        "Sun Level" : "阳光水平",
        "Growth Level" : "生长水平",
        "Save" : "保存",
        "Load" : "加载",
        "Next Turn" : "下一回合",
        "Slot One" : "插槽一",
        "Slot Two" : "插槽二",
        "Slot Three" : "插槽三",
        "Slot Four" : "插槽四",
        "Language": "语言",
        "Select a plant species": "选择一种植物种类",
        "Select a Language": "选择一种语言",
        "Cell i" : "单元格 i",
        "Cell j" : "单元格 j",
        "Planterbox" : "种植箱",
        "Game is automatically saved after every turn, but you can manually save at any point": "游戏在每个回合后自动保存，但您可以在任何时候手动保存"
    },
    fa: {
        "Reap": "درو کردن",
        "Sow": "کاشتن",
        "Up": "بالا",
        "Down": "پایین",
        "Left": "چپ",
        "Right": "راست",
        "Undo": "واگرد",
        "Redo": "از نو انجام دادن",
        "Plant Species": "گونه‌های گیاهی",
        "Aloe Vera": "آلوئه‌ورا",
        "Wheat": "گندم",
        "Venus Flytrap": "گیاه حشره‌خوار ونوس",
        "Water Level": "سطح آب",
        "Sun Level": "سطح نور خورشید",
        "Growth Level": "سطح رشد",
        "Save": "ذخیره",
        "Load": "بارگذاری",
        "Next Turn": "نوبت بعدی",
        "Slot One": "شکاف یک",
        "Slot Two": "شکاف دو",
        "Slot Three": "شکاف سه",
        "Slot Four": "شکاف چهار",
        "Language": "زبان",
        "Select a plant species": "گونه گیاهی را انتخاب کنید",
        "Select a Language": "زبان را انتخاب کنید",
        "Cell i": "سلول i",
        "Cell j": "سلول j",
        "Planterbox": "جعبه کاشت",
        "Game is automatically saved after every turn, but you can manually save at any point": "ازی به صورت خودکار پس از هر نوبت ذخیره می‌شود، اما شما می‌توانید به صورت دستی در هر زمانی ذخیره کنید"
      }
}