export const languageNames = [
  { code: "en", displayName: "English", orientation: "left" },
  { code: "fa", displayName: "فارسی", orientation: "right" },
  { code: "cn", displayName: "中文", orientation: "left" },
];

export const translationObject: TranslateObject = {
  en: {
    "Reap": "Reap",
    "Sow": "Sow",
    "Up": "Up",
    "Down": "Down",
    "Left": "Left",
    "Right": "Right",
    "Undo": "Undo",
    "Redo": "Redo",
    "Plant Species": "Plant Species",
    "Aloe Vera": "Aloe Vera",
    "Wheat": "Wheat",
    "Flytrap": "Flytrap",
    "Water Level": "Water Level",
    "Sun Level": "Sun Level",
    "Growth Level": "Growth Level",
    "Save": "Save",
    "Load": "Load",
    "Next Turn": "Next Turn",
    "Slot 1": "Slot 1",
    "Slot 2": "Slot 2",
    "Slot 3": "Slot 3",
    "Slot 4": "Slot 4",
    "Language": "Language",
    "Select a plant species": "Select a plant species",
    "Select a planterbox": "",
    "Select a Language": "Select a Language",
    "Cell i": "Cell i",
    "Cell j": "Cell j",
    "Cell": "Cell",
    "Planterbox": "Planterbox",
    "Selected PlanterBox": "",
    "No Cell Selected": "No Cell Selected",
    "none": "none",
    "Game is automatically saved after every turn, but you can manually save at any point":
      "Game is automatically saved after every turn, but you can manually save at any point",
    "Loading": "Loading",
    "Loading Cells ...": "Loading Cells ...",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
  },
  cn: {
    "Reap": "收割",
    "Sow": "播种",
    "Up": "上",
    "Down": "下",
    "Left": "左",
    "Right": "右",
    "Undo": "撤销",
    "Redo": "重做",
    "Plant Species": "植物种类",
    "Aloe Vera": "芦荟",
    "Wheat": "小麦",
    "Flytrap": "捕蝇草",
    "Water Level": "水位",
    "Sun Level": "阳光水平",
    "Growth Level": "生长水平",
    "Save": "保存",
    "Load": "加载",
    "Next Turn": "下一回合",
    "Slot 1": "插槽 一",
    "Slot 2": "插槽 二",
    "Slot 3": "插槽 三",
    "Slot 4": "插槽 四",
    "Language": "语言",
    "Select a plant species": "选择一种植物种类",
    "Select a planterbox": "选择种植箱",
    "Select a Language": "选择一种语言",
    "Cell i": "单元格 i",
    "Cell j": "单元格 j",
    "Cell": "单元格",
    "Planterbox": "种植箱",
    "Selected PlanterBox": "已选择的种植箱",
    "No Cell Selected": "没有选择任何单元格",
    "none": "无",
    "Game is automatically saved after every turn, but you can manually save at any point":
      "游戏会在每回合后自动保存，但您可以随时手动保存",
    "Loading": "加载中",
    "Loading Cells ...": "加载单元格 。。。",
    "0": "零",
    "1": "一",
    "2": "二",
    "3": "三",
    "4": "四",
    "5": "五",
    "6": "六",
    "7": "七",
    "8": "8",
    "50": "五十",
    "75": "七十五",
    "100": "一百",
    "110": "一百一十",
    "125": "一百二十五",
    "150": "一百五十",
    "175": "一百七十五",
    "200": "二百",
    "225": "二百二十五",
  },
  fa: {
    "Reap": "درو کردن",
    "Sow": "کاشتن",
    "Up": "بالا",
    "Down": "پایین",
    "Left": "چپ",
    "Right": "راست",
    "Undo": "بازگرداندن",
    "Redo": "انجام دوباره",
    "Plant Species": "گونه‌های گیاهی",
    "Aloe Vera": "آلوئه‌ورا",
    "Wheat": "گندم",
    "Flytrap": "گیاه گوشت‌خوار",
    "Water Level": "سطح آب",
    "Sun Level": "سطح نور خورشید",
    "Growth Level": "سطح رشد",
    "Save": "ذخیره",
    "Load": "بارگذاری",
    "Next Turn": "نوبت بعدی",
    "Slot 1": "جایگاه ۱",
    "Slot 2": "جایگاه ۲",
    "Slot 3": "جایگاه ۳",
    "Slot 4": "جایگاه ۴",
    "Language": "زبان",
    "Select a plant species": "یک گونه گیاهی انتخاب کنید",
    "Select a planterbox": "یک جعبه کاشت انتخاب کنید",
    "Select a Language": "یک زبان انتخاب کنید",
    "Cell i": "سلول i",
    "Cell j": "سلول j",
    "Cell": "سلول",
    "Planterbox": "جعبه کاشت",
    "Selected PlanterBox": "جعبه کاشت انتخاب شده",
    "No Cell Selected": "هیچ سلولی انتخاب نشده است",
    "none": "هیچکدام",
    "Game is automatically saved after every turn, but you can manually save at any point":
      "بازی به طور خودکار بعد از هر نوبت ذخیره می‌شود، اما می‌توانید هر لحظه به صورت دستی ذخیره کنید",
    "Loading": "در حال بارگذاری",
    "Loading Cells ...": "...در حال بارگذاری سلول‌ها",
    "1": "۱",
    "2": "۲",
    "3": "۳",
    "4": "۴",
    "5": "۵",
    "6": "۶",
    "7": "۷",
    "8": "۸",
    "50": "پنجاه",
    "75": "هفتاد و پنج",
    "100": "صد",
    "110": "صد و ده",
    "125": "صد و بیست و پنج",
    "150": "صد و پنجاه",
    "175": "صد و هفتاد و پنج",
    "200": "دویست",
    "225": "دویست و بیست و پنج",
  },
};

export default function getTranslation(
  key: string,
  currentLanguage: string,
) {
  if (
    translationObject[currentLanguage] &&
    translationObject[currentLanguage][key]
  ) {
    return translationObject[currentLanguage][key];
  }
  return key;
}
